'use strict';

const constants = {
  ROL_SUPER_ADMIN                    : 1,
  ROL_ADMIN                          : 2,
  ROL_PROSPECTO                      : 8,
  ESTADO_ACTIVO                      : 'ACTIVO',
  CARGO_USUARIO                      : 'CIUDADANO',
  USUARIO_CREACION_DEFAULT           : 1,
  TIPO_PERSONA_NATURAL               : 74,
  TIPO_PERSONA_JURIDICA              : 75,
  // TIPO UNIDAD ECONOMICA
  TIPO_UNIDAD_ECONOMICA_UNIPERSONAL  : 73,
  TIPO_UNIDAD_ECONOMICA_SRL          : 50,
  TIPO_UNIDAD_ECONOMICA_SA           : 47,
  // TIPO UNIDAD ECONOMICA
  // TIPO CONFORMACION
  TIPO_CONFORMACION_ACCIONES         : 30,
  TIPO_CONFORMACION_CUOTAS           : 31,
  // TIPO CONFORMACION
  TIPO_PODER_GENERAL                 : 28,
  EMPRESA_ESTADO_SIN_VERIFICAR       : 'SIN_VERIFICAR',
  EMPRESA_ESTADO_VERFICICADO         : 'VERIFICADO',
  ROL_SOLICITANTE_EMPRESA_DIGITAL    : '000000000000000000000111',
  TIPO_ENTITY_EMPRESA_DIGITAL        : 'empresa',
  JWT_TOKEN_EXPIRATION               : 240,
  TIPO_DOCUMENTO_CI                  : 77,
  TIPO_DOCUMENTO_CI_EXTRANJERIA      : 76,
  // CASA MATRIZ
  TIPO_ESTABLECIMIENTO_CASA_MATRIZ   : 27,
  NOMBRE_ESTABLECIMIENTO_CASA_MATRIZ : 'DOMICILIO FISCAL'
};

module.exports = constants;
